-- SET REFERENTIAL_INTEGRITY FALSE;
-- TRUNCATE TABLE urls RESTART IDENTITY;
-- TRUNCATE TABLE url_checks RESTART IDENTITY;
-- SET REFERENTIAL_INTEGRITY TRUE;
TRUNCATE TABLE urls RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE url_checks RESTART IDENTITY  CASCADE;

